Matrix Multipilaction Using Pytorch

In [18]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Matrix Multiplication

In [19]:
tensor1 = torch.tensor([4,5,6])
tensor2 = torch.tensor([7,1,4])

In [20]:
tensor1 * tensor2

tensor([28,  5, 24])

In [21]:
tensor3 = torch.tensor([[1,2,3],[4,5,6]])
tensor4 = torch.tensor([[7,8],
                       [9,10],
                       [11,12]])

In [22]:
torch.matmul(tensor3,tensor4)

tensor([[ 58,  64],
        [139, 154]])

In [23]:
tns1 = torch.tensor([[11,5,14],
                     [21,14,19],
                     [26,31,25]])
tns2 = torch.tensor([[6,11,26],
                     [34,15,18],
                     [19,28,32]])

In [24]:
torch.matmul(tns1,tns2)

tensor([[ 502,  588,  824],
        [ 963,  973, 1406],
        [1685, 1451, 2034]])

In [25]:
tensora = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensorb = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

Error!

In [27]:
torch.matmul(tensora,tensorb)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

How to fix this error:

In [28]:
tensorb.T, tensorb.T

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]))

In [15]:
torch.matmul(tensora,tensorb.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [16]:
torch.min(tns1)

tensor(5)

In [17]:
torch.max(tns1)


tensor(31)