![Alt text](./images/tensor.jpg?raw=true "Title")

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Float32 Tensor

In [3]:
floatensor = torch.tensor([3.0, 4.0, 5.0, 6.0],
                          dtype=torch.float32,
                          device=torch.device('cuda'),
                          requires_grad=False)
floatensor

tensor([3., 4., 5., 6.], device='cuda:0')

Float16 Tensor

In [4]:
flot16 = floatensor.type(torch.float16)
flot16

tensor([3., 4., 5., 6.], device='cuda:0', dtype=torch.float16)

Int32 Tensor

In [5]:
in32ten = torch.tensor([3, 4, 5, 6], dtype=torch.int32
                       , device=torch.device('cuda'), requires_grad=False)
in32ten

tensor([3, 4, 5, 6], device='cuda:0', dtype=torch.int32)

In [13]:

tensor1 = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32,)

In [14]:
tensor1 + 10

tensor([[11., 12., 13.],
        [14., 15., 16.]])

In [16]:
tensor1 * 100

tensor([[100., 200., 300.],
        [400., 500., 600.]])

In [17]:
tensor1 - 14

tensor([[-13., -12., -11.],
        [-10.,  -9.,  -8.]])

In [19]:
#multiply function

torch.mul(tensor1, 10)

tensor([[10., 20., 30.],
        [40., 50., 60.]])

In [20]:
#tambah
torch.add(tensor1, 10)

tensor([[11., 12., 13.],
        [14., 15., 16.]])

In [21]:
#ngebagi
torch.div(tensor1, 2)

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])