Bikin Tensor

In [2]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
!nvidia-smi

/bin/bash: /home/aezx/miniconda3/lib/libtinfo.so.6: no version information available (required by /bin/bash)
Tue Sep 26 17:28:14 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.98.01              Driver Version: 536.99       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4060 ...    On  | 00000000:01:00.0  On |                  N/A |
| N/A   45C    P8               2W /  80W |    268MiB /  8188MiB |     20%      Default |
|                                         |      

In [8]:
#scalar
scalar = torch.tensor(3)
print(scalar)
print(type(scalar))
scalar.ndim

tensor(3)
<class 'torch.Tensor'>


0

In [11]:
#vector
vector = torch.tensor([1,2,3,4,5])
print(type(vector))
vector.ndim

<class 'torch.Tensor'>


1

In [15]:
#MATRIX
matrix = torch.tensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
print(matrix)
matrix.ndim

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


2

In [30]:
#tensor
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]],
                       [[6,2,3],
                        [4,5,6],
                        [7,8,9]],
                        [[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
print(tensor)
tensor.ndim

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[6, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


3

In [31]:
tensor.shape

torch.Size([3, 3, 3])

In [34]:
#Random tensor Float
rand = torch.rand(7,4)
print(rand)

tensor([[0.8978, 0.8662, 0.7522, 0.2543],
        [0.3949, 0.5738, 0.1029, 0.3664],
        [0.9322, 0.4140, 0.7218, 0.6964],
        [0.8774, 0.4316, 0.4916, 0.0330],
        [0.0467, 0.0591, 0.9285, 0.7435],
        [0.3012, 0.9838, 0.7347, 0.9110],
        [0.6079, 0.6045, 0.5352, 0.4331]])


In [39]:
#Random tensor Int
randint = torch.randint(0,10,(7,4))
print(randint)

tensor([[3, 4, 2, 7],
        [4, 5, 1, 4],
        [8, 2, 0, 5],
        [8, 7, 1, 9],
        [7, 9, 2, 2],
        [6, 5, 1, 4],
        [7, 0, 5, 0]])
